#!/usr/bin/env bash

sudo rm -rf var/cache/*
# scripts/console cache:clear --no-warmup
scripts/console doctrine:database:drop --force
scripts/console doctrine:database:create --if-not-exists
scripts/console doctrine:schema:create
#scripts/console doctrine:fixtures:load -n

#my
sudo chmod 777 -R var/cache