services:

    app.subscriber:
        class: AppBundle\EventListener\AppSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }

    app.locale.listener:
        class: AppBundle\EventListener\LocaleListener
        arguments:
          - "%kernel.default_locale%"
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 17 }

    app.form.type.locale:
        class: AppBundle\Form\LocaleType
        arguments:
            - "%supported_lang%"
        tags:
            - { name: form.type }

    menu_locale_title.twig_extension:
        class: AppBundle\Twig\Extension\MenuLocaleTitle
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@request_stack"
        tags:
          - { name: twig.extension }

    app.twig.extension:
        class: AppBundle\Twig\Extension\EasyAdminTwigExtension
        arguments:
            - "@easyadmin.config.manager"
            - "@property_accessor"
            - "%kernel.debug%"
            - "@security.authorization_checker"
        tags:
          - { name: twig.extension }