#sonata_block:
#  default_context: [cms]
#  blocks:
#    sonata.admin.block.admin_list:
#      context: [admin]

parameters:
  locale: en
#  sonata.user.admin.user.class: AppBundle\Admin\UserAdmin
#  sonata.user.admin.user.entity: AppBundle\Entity\User
#
#services:
#    sonata.user.admin.group:
#        abstract: true
#        public: false

sonata_block:
#  default_contexts: [sonata_page_bundle]
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]
    sonata.user.block.menu:    # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
    handler: sonata.admin.security.handler.acl

#  templates:
#    dashboard: SonataAdminBundle:Core:dashboard.html.twig

sonata_user:
#todo
#  class:
#    user: AppBundle\Entity\User
  security_acl: true
  manager_type: orm
